added node for depth sensor, does not read values from sensor yet
uvic-auvic/polaris_2018 pull request #27
Opened 2018-03-10 22:58 UTC by colemacdonald

2018-03-11 02:39 UTC, KeiferE-zz requested changes
Some notes:
-thanks for adding a launchfile!
-I think we want to use ros spinonce instead of spin. Read here: http://wiki.ros.org/roscpp/Overview/Callbacks%20and%20Spinning I think we want to use the practice of periodically checking for callbacks. I could be wrong though. 
-the using namespace std is not needed. You make now calls to the std library. Also because it is a general library and names are simple you don't want the functions undefined. I will try to find an explanation that is better online and send it too you.
-the second argument for advertise just encase you did not know is the amount of messages buffered before overwriting throwing old ones away. Depending on your loop rate and message this could be important. I think for what we are sending this is fine, but just so you know for future nodes.

2018-03-11 03:46 UTC, asinha94 requested changes
Generally good, you just need to get the hang of the ROS idiomatic way of doing things., Take a look at the comments in each section and let me know if you have any other questions.

2018-03-11 03:46 UTC, asinha94 commented on ros/src/depth_sensor/package.xml
> +  <build_depend>roscpp</build_depend>
You don't actually need to include roscpp or rospy as build or run depenendencies, they get added automatically, but it doesn't really matter, just an FYI.

2018-03-11 03:46 UTC, asinha94 commented on ros/src/depth_sensor/src/depth_sensor_node.cpp
> +using namespace std;
I agree with Keifer, we don;t like using namespaces in general, especially std as it hides information such as where functions come from and the compiler may not be able to determine what is being used and what isn't.  You're also not actually using the std lib so it can be removed

2018-03-11 03:46 UTC, asinha94 commented on ros/src/depth_sensor/src/depth_sensor_node.cpp
> +ros::Publisher pub;
Don't make the publisher global. Im actually surprised this worked because I once tried to make a service global and it threw hundreds of errors. In this case the depth sensor is just spitting things out so it doesn't need to be accessed by anyone so keep its scope to main.

2018-03-11 03:46 UTC, asinha94 commented on ros/src/depth_sensor/src/depth_sensor_node.cpp
> +    ros::NodeHandle nh;
replace this with `ros::NodeHandle nh("~")`. What that does is creates a nodehandle in the namespace of your project. I.e  it easier to access other pub/subs and services in the same package. It also uses the ROS standard way of pub/sub names. It's nitpicky but is actually better when the codebase gets larger.

2018-03-11 03:46 UTC, asinha94 commented on ros/src/depth_sensor/src/depth_sensor_node.cpp
> +    ros::Rate r(10); // 10 Hz
If you know how, can you add the parameter (the loop rate) to the launchfile. Take a look [here](https://github.com/uvic-auvic/RedHerring/blob/09a6bc4fd5be63207280bc9de4f0213cf417fd3d/ros/src/motor_controller/src/controller.cpp#L285) on how to read from a launchfile

2018-03-11 03:46 UTC, asinha94 commented on ros/src/depth_sensor/src/depth_sensor_node.cpp
> +    ros::spin();
this needs to be inside the loop after the sleep, and instead of `ros::spin()` it should be `ros:;spinOnce()`. `Spin()` blocks untill ros shutsdown and checks whether any of your callbackcs have been called called and wherther we need to send anything. `SpinOnce()` as you can probably tell just checks everything once then gets on with the program.

2018-03-12 05:01 UTC, KeiferE commented on ros/src/depth_sensor/CMakeLists.txt
> +<<<<<<< HEAD
I think there is a commit issue that got through here so there is a duplicate dependency

2018-03-15 01:37 UTC, KeiferE-zz approved these changes

2018-03-15 02:37 UTC, asinha94 approved these changes

2018-03-22 02:47 UTC, merged